options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/dc-cloud-451321/inft1210assign2-flask/inft1210assign2-flask:latest', '.']
  
  # Step 2: Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/dc-cloud-451321/inft1210assign2-flask/inft1210assign2-flask:latest']

  # Step 3: Restart the container on Compute Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'mihir-app-instance'
      - '--zone=us-central1-a'
      - '--command=docker stop $(docker ps -q) && docker run -d -p 5000:5000 gcr.io/dc-cloud-451321/inft1210assign2-flask/inft1210assign2-flask:latest'
